apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-mlflow-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mlops-disease-predictor
  template:
    metadata:
      labels:
        app: mlops-disease-predictor
    spec:
      containers:
      - name: mlops-disease-predictor
        image: sudhsakhala/mlops-disease-predictor:latest
        ports:
        - containerPort: 8001
        - containerPort: 5001
        env:
        - name: PYTHONDONTWRITEBYTECODE
          value: "1"
        - name: PYTHONUNBUFFERED
          value: "1"
        volumeMounts:
        - name: mlops-storage
          mountPath: /mlflow
      volumes:
      - name: mlops-storage
        persistentVolumeClaim:
          claimName: mlops-pvc
